#!/usr/bin/env python3
"""Generate Go and Python SDK model types from the OpenAPI schemas."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import subprocess
import sys

import yaml


ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "docs" / "openapi.yaml"
GO_OUTPUT = ROOT / "sdk-go" / "models.gen.go"
PY_OUTPUT = ROOT / "sdk-python" / "src" / "nexora" / "models.py"


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.replace("-", "_").split("_"))


def referenced_type(schema: dict) -> str | None:
    ref = schema.get("$ref")
    if ref:
        return ref.rsplit("/", 1)[-1]
    for part in schema.get("allOf", []):
        if "$ref" in part:
            return part["$ref"].rsplit("/", 1)[-1]
    return None


def go_type(schema: dict) -> str:
    ref = referenced_type(schema)
    if ref:
        return ref
    kind = schema.get("type")
    if kind == "array":
        return "[]" + go_type(schema.get("items", {}))
    if kind == "object":
        value = schema.get("additionalProperties")
        return "map[string]" + go_type(value) if isinstance(value, dict) else "map[string]any"
    return {
        "string": "string",
        "integer": "int64",
        "number": "float64",
        "boolean": "bool",
    }.get(kind, "any")


def python_type(schema: dict) -> str:
    ref = referenced_type(schema)
    if ref:
        return ref
    kind = schema.get("type")
    if kind == "array":
        return f"list[{python_type(schema.get('items', {}))}]"
    if kind == "object":
        value = schema.get("additionalProperties")
        return f"dict[str, {python_type(value)}]" if isinstance(value, dict) else "dict[str, Any]"
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
    }.get(kind, "Any")


def properties(schema: dict) -> dict:
    result = dict(schema.get("properties", {}))
    for part in schema.get("allOf", []):
        result.update(part.get("properties", {}))
    return result


def required_properties(schema: dict) -> set[str]:
    result = set(schema.get("required", []))
    for part in schema.get("allOf", []):
        result.update(part.get("required", []))
    return result


def base_types(schema: dict) -> list[str]:
    return [part["$ref"].rsplit("/", 1)[-1] for part in schema.get("allOf", []) if "$ref" in part]


def generate(spec: dict) -> tuple[str, str]:
    schemas = spec["components"]["schemas"]
    digest = hashlib.sha256(SPEC.read_bytes()).hexdigest()
    go_lines = [
        "// Code generated by tools/sdkgen.py; DO NOT EDIT.",
        f"// OpenAPI SHA256: {digest}",
        "package nexora",
        "",
    ]
    py_lines = [
        "# Code generated by tools/sdkgen.py; DO NOT EDIT.",
        f"# OpenAPI SHA256: {digest}",
        "from __future__ import annotations",
        "",
        "from typing import Any, Required, TypedDict",
        "",
    ]

    for name, schema in schemas.items():
        base = base_types(schema)
        fields = properties(schema)
        required = required_properties(schema)
        go_lines.append(f"type {pascal(name)} struct {{")
        for parent in base:
            go_lines.append(f"\t{pascal(parent)}")
        for key, field in fields.items():
            typ = go_type(field)
            optional = key not in required
            if optional and typ not in ("any",) and not typ.startswith("[]") and not typ.startswith("map["):
                typ = "*" + typ
            tag = f'json:"{key}' + (",omitempty" if optional else "") + '"'
            go_lines.append(f"\t{pascal(key)} {typ} `{tag}`")
        if not base and not fields:
            go_lines.append("\tmap[string]any")
        go_lines.extend(["}", ""])

        py_base = ", ".join(pascal(parent) for parent in base) or "TypedDict"
        py_lines.append(f"class {pascal(name)}({py_base}, total=False):")
        for key, field in fields.items():
            typ = python_type(field)
            if field.get("nullable"):
                typ += " | None"
            if key in required:
                py_lines.append(f"    {key}: Required[{typ}]")
            else:
                py_lines.append(f"    {key}: {typ}")
        if not fields and not base:
            py_lines.append("    pass")
        py_lines.append("")

    go_source = subprocess.run(
        ["gofmt"], input="\n".join(go_lines), text=True, capture_output=True, check=True
    ).stdout
    return go_source, "\n".join(py_lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()
    generated = dict(zip((GO_OUTPUT, PY_OUTPUT), generate(yaml.safe_load(SPEC.read_text()))))
    stale = []
    for path, content in generated.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("Generated SDK models are stale:", *(str(path) for path in stale), sep="\n  ", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())