# Code generated by tools/sdkgen.py; DO NOT EDIT.
# OpenAPI SHA256: 32be0346d7f4e4fe0014972d0b821e3229377d92d6ab3bf5330a534ce8938d23
from __future__ import annotations

from typing import Any, Required, TypedDict

class Beneficiary(TypedDict, total=False):
    id: Required[str]
    account: Required[str]
    label: str
    status: Required[str]
    cooldown_until: Required[str]
    created_at: Required[str]
    updated_at: Required[str]

class CreateBeneficiaryRequest(TypedDict, total=False):
    account: Required[str]
    label: str

class ComplianceReview(TypedDict, total=False):
    id: str
    transaction_id: str
    status: str
    risk_score: int
    rules_fired: list[str]
    reason: str
    reviewed_by: str
    review_notes: str
    reviewed_at: str
    created_at: str

class SanctionsStatus(TypedDict, total=False):
    loaded: bool
    entity_count: int
    address_count: int
    name_count: int
    updated_at: str
    last_refresh: dict[str, Any]

class ErrorResponse(TypedDict, total=False):
    error: Required[dict[str, Any]]

class HealthResponse(TypedDict, total=False):
    status: str
    services: dict[str, str]

class MetricsResponse(TypedDict, total=False):
    started_at: str
    total_requests: int
    active_requests: int
    total_errors: int
    uptime_seconds: float
    requests_by_code: dict[str, int]

class RegisterRequest(TypedDict, total=False):
    name: Required[str]
    email: Required[str]
    password: Required[str]

class LoginRequest(TypedDict, total=False):
    email: Required[str]
    password: Required[str]

class AuthResponse(TypedDict, total=False):
    tenant_id: str
    api_key: str
    name: str
    email: str
    created_at: str

class CreateKeyRequest(TypedDict, total=False):
    label: str | None
    scopes: list[str]

class APIKeyCreated(TypedDict, total=False):
    id: str
    key: str
    prefix: str
    label: str | None
    scopes: list[str]
    created_at: str

class APIKeySummary(TypedDict, total=False):
    id: str
    prefix: str
    label: str | None
    scopes: list[str]
    last_used_at: str | None
    revoked_at: str | None
    created_at: str

class Wallet(TypedDict, total=False):
    id: str
    public_key: str
    created_at: str

class WalletCreated(TypedDict, total=False):
    id: str
    public_key: str
    created_at: str

class WalletBalances(TypedDict, total=False):
    wallet_id: str
    balances: list[Balance]

class Balance(TypedDict, total=False):
    asset_code: str
    issuer: str
    balance: str

class CreateTrustlineRequest(TypedDict, total=False):
    asset_code: Required[str]
    asset_issuer: Required[str]
    limit: str

class TrustlineResponse(TypedDict, total=False):
    wallet_id: str
    asset_code: str
    asset_issuer: str
    status: str

class FiatQuotePreviewResponse(TypedDict, total=False):
    provider: str
    fiat_amount: str
    fiat_currency: str
    usdc_amount: str
    rate: str
    fee: str
    min_limit: str
    max_limit: str
    expires_at: str

class FiatDepositRequest(TypedDict, total=False):
    amount: Required[str]
    currency: Required[str]
    email: Required[str]
    name: Required[str]

class CreatePaymentLinkRequest(TypedDict, total=False):
    wallet_id: Required[str]
    amount: Required[str]
    currency: Required[str]
    expires_at: Required[str]

class PaymentLinksResponse(TypedDict, total=False):
    payment_links: Required[list[PaymentLink]]

class PaymentLink(TypedDict, total=False):
    id: Required[str]
    token: Required[str]
    wallet_id: Required[str]
    amount: Required[str]
    currency: Required[str]
    status: Required[str]
    checkout_url: Required[str]
    expires_at: Required[str]
    created_at: str

class PublicPaymentLink(TypedDict, total=False):
    amount: Required[str]
    currency: Required[str]
    status: Required[str]
    expires_at: Required[str]

class Refund(TypedDict, total=False):
    id: Required[str]
    original_transaction_id: Required[str]
    transaction_id: str
    amount: Required[str]
    reason: str
    status: Required[str]

class CreateRefundRequest(TypedDict, total=False):
    original_transaction_id: Required[str]
    amount: Required[str]
    reason: str

class RefundsResponse(TypedDict, total=False):
    refunds: Required[list[Refund]]

class DepositResponse(TypedDict, total=False):
    payment_link: str
    reference: str

class FiatWithdrawalRequest(TypedDict, total=False):
    amount: Required[str]
    currency: Required[str]
    account_bank: Required[str]
    account_number: Required[str]

class WithdrawalResponse(TypedDict, total=False):
    reference: str
    status: str

class FiatDeposit(TypedDict, total=False):
    id: str
    wallet_id: str
    provider: str
    provider_reference: str
    fiat_amount: str
    fiat_currency: str
    usdc_amount: str
    status: str
    created_at: str

class FiatWithdrawal(TypedDict, total=False):
    id: str
    wallet_id: str
    provider: str
    provider_reference: str
    fiat_amount: str
    fiat_currency: str
    usdc_amount: str
    status: str
    created_at: str

class CreateTransferRequest(TypedDict, total=False):
    from_wallet_id: Required[str]
    to_wallet_id: Required[str]
    asset: Required[str]
    amount: Required[str]
    external_reference: str | None
    tags: list[str]

class TransferResponse(TypedDict, total=False):
    id: str
    tx_hash: str
    type: str
    status: str
    from_wallet_id: str
    to_wallet_id: str
    asset: str
    amount: str
    fee_amount: str
    net_amount: str
    fee_bps: int
    external_reference: str | None
    tags: list[str]
    failure_reason: str
    failure_message: str
    created_at: str

class AuditEvent(TypedDict, total=False):
    id: str
    tenant_id: str
    mode: str
    actor_type: str
    actor_id: str
    action: str
    resource_type: str
    resource_id: str
    metadata: dict[str, Any]
    ip_address: str | None
    user_agent: str | None
    created_at: str

class AuditListResponse(TypedDict, total=False):
    events: list[AuditEvent]
    total: int
    limit: int
    offset: int

class CreateBatchRequest(TypedDict, total=False):
    from_wallet_id: Required[str]
    transfers: Required[list[BatchItemRequest]]

class BatchItemRequest(TypedDict, total=False):
    to_wallet_id: Required[str]
    asset: Required[str]
    amount: Required[str]
    reference: str

class BatchResponse(TypedDict, total=False):
    id: str
    status: str
    total_count: int
    success_count: int
    failed_count: int
    held_count: int
    created_at: str
    transfers: list[BatchTransferItem]

class BatchTransferItem(TypedDict, total=False):
    id: str
    to_wallet_id: str
    asset: str
    amount: str
    reference: str | None
    status: str
    tx_hash: str | None
    failure_reason: str
    failure_message: str

class QuoteRequest(TypedDict, total=False):
    from_asset: Required[str]
    to_asset: Required[str]
    amount: Required[str]

class Quote(TypedDict, total=False):
    id: str
    org_id: str
    from_asset: str
    to_asset: str
    from_amount: str
    to_amount: str
    rate: str
    fee: str
    expires_at: str
    used: bool

class ConvertRequest(TypedDict, total=False):
    wallet_id: Required[str]
    quote_id: Required[str]
    min_amount_out: str
    max_slippage_bps: int

class ConversionResponse(TypedDict, total=False):
    id: str
    wallet_id: str
    source_asset: str
    dest_asset: str
    source_amount: str
    dest_amount: str
    fee_amount: str
    fee_bps: int
    rate: str
    tx_hash: str
    created_at: str

class RateResponse(TypedDict, total=False):
    rate: str
    mid_market_rate: str
    spread_bps: int
    provider: str
    cached_at: str
    stale: bool
    source_amount: str
    dest_amount: str
    fee_amount: str
    net_amount: str
    fee_bps: int

class CreateScheduleRequest(TypedDict, total=False):
    from_wallet_id: Required[str]
    to_wallet_id: Required[str]
    asset: Required[str]
    amount: Required[str]
    frequency: Required[str]
    timezone: str
    missed_run_policy: str
    start_date: Required[str]
    end_date: str

class ScheduleRunResponse(TypedDict, total=False):
    id: str
    schedule_id: str
    expected_run_at: str
    status: str
    transaction_id: str | None
    error: str
    started_at: str
    completed_at: str
    created_at: str

class UpdateScheduleRequest(TypedDict, total=False):
    status: str
    amount: str
    frequency: str
    end_date: str
    timezone: str
    missed_run_policy: str

class ScheduleResponse(TypedDict, total=False):
    id: str
    from_wallet_id: str
    to_wallet_id: str
    asset: str
    amount: str
    frequency: str
    timezone: str
    missed_run_policy: str
    next_run_at: str
    end_at: str | None
    status: str
    created_at: str

class RegisterWebhookRequest(TypedDict, total=False):
    url: Required[str]
    events: list[str]

class WebhookEndpointResponse(TypedDict, total=False):
    id: str
    url: str
    secret: str
    events: list[str]
    active: bool
    created_at: str

class WebhookEndpointSummary(TypedDict, total=False):
    id: str
    url: str
    events: list[str]
    active: bool
    created_at: str

class WebhookDelivery(TypedDict, total=False):
    id: str
    endpoint_id: str
    event_type: str
    status: str
    response_code: int | None
    attempt_count: int
    last_attempt: str | None
    created_at: str

class FeeScheduleResponse(TypedDict, total=False):
    transfer_fee_bps: int
    conversion_fee_bps: int
    min_fee_amount: str
    max_fee_amount: str | None
    asset: str

class FeeCollectionSummary(TypedDict, total=False):
    asset: str
    total_fees: str
    tenant_fees: list[TenantFeeTotal]

class TenantFeeTotal(TypedDict, total=False):
    tenant_id: str | None
    total_fees: str

class ClaimPredicate(TypedDict, total=False):
    type: Required[str]
    timestamp: int
    seconds: int
    predicates: list[ClaimPredicate]

class Claimant(TypedDict, total=False):
    account: Required[str]
    predicate: ClaimPredicate

class CreateClaimableBalanceRequest(TypedDict, total=False):
    asset: Required[str]
    amount: Required[str]
    claimants: Required[list[Claimant]]
    source_wallet_id: str
    sponsor_account: str
    revoke_on_expiry: bool
    expires_at: str

class CreateClaimableBalanceResponse(TypedDict, total=False):
    balance_id: str
    reserve_required: str
    sponsored: bool
    tx_hash: str
    expires_at: str | None

class ClaimableBalanceResponse(TypedDict, total=False):
    id: str
    asset: str
    amount: str
    claimants: list[Claimant]
    sponsor: str
    status: str
    revoke_on_expiry: bool
    created_at: str
    expires_at: str | None
    claimed_at: str | None
    claimed_by: str

class LiveClaimableBalanceResponse(ClaimableBalanceResponse, total=False):
    claimable: bool
    on_chain: dict[str, Any] | None

class ClaimClaimableBalanceRequest(TypedDict, total=False):
    claimant_account: str

class ClaimClaimableBalanceResponse(TypedDict, total=False):
    balance_id: str
    claimed_by: str
    amount: str
    tx_hash: str
    status: str

class UsageResponse(TypedDict, total=False):
    total_requests: int
    requests_today: int
    transfers_count: int
    conversions_count: int
    batches_count: int

class ReconciliationSummary(TypedDict, total=False):
    days: list[DailySummaryRow]
    total_ok: int
    total_mismatch: int
    total_not_found: int
    pending_stuck: int

class DailySummaryRow(TypedDict, total=False):
    date: str
    ok: int
    mismatch: int
    not_found: int

class IdempotencyInspectionResponse(TypedDict, total=False):
    key: Required[str]
    status: Required[str]
    created_at: str
    expires_at: str
    request_hash: str
    retry_after_seconds: int
    retry_hint: str
    response: IdempotencyStoredResponse

class IdempotencyStoredResponse(TypedDict, total=False):
    status: Required[int]
    headers: dict[str, list[str]]
    body: Any
    body_text: str
    body_truncated: Required[bool]
    body_size_bytes: Required[int]
