// Code generated by tools/sdkgen.py; DO NOT EDIT.
// OpenAPI SHA256: 32be0346d7f4e4fe0014972d0b821e3229377d92d6ab3bf5330a534ce8938d23
package nexora

type Beneficiary struct {
	Id            string  `json:"id"`
	Account       string  `json:"account"`
	Label         *string `json:"label,omitempty"`
	Status        string  `json:"status"`
	CooldownUntil string  `json:"cooldown_until"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type CreateBeneficiaryRequest struct {
	Account string  `json:"account"`
	Label   *string `json:"label,omitempty"`
}

type ComplianceReview struct {
	Id            *string  `json:"id,omitempty"`
	TransactionId *string  `json:"transaction_id,omitempty"`
	Status        *string  `json:"status,omitempty"`
	RiskScore     *int64   `json:"risk_score,omitempty"`
	RulesFired    []string `json:"rules_fired,omitempty"`
	Reason        *string  `json:"reason,omitempty"`
	ReviewedBy    *string  `json:"reviewed_by,omitempty"`
	ReviewNotes   *string  `json:"review_notes,omitempty"`
	ReviewedAt    *string  `json:"reviewed_at,omitempty"`
	CreatedAt     *string  `json:"created_at,omitempty"`
}

type SanctionsStatus struct {
	Loaded       *bool          `json:"loaded,omitempty"`
	EntityCount  *int64         `json:"entity_count,omitempty"`
	AddressCount *int64         `json:"address_count,omitempty"`
	NameCount    *int64         `json:"name_count,omitempty"`
	UpdatedAt    *string        `json:"updated_at,omitempty"`
	LastRefresh  map[string]any `json:"last_refresh,omitempty"`
}

type ErrorResponse struct {
	Error map[string]any `json:"error"`
}

type HealthResponse struct {
	Status   *string           `json:"status,omitempty"`
	Services map[string]string `json:"services,omitempty"`
}

type MetricsResponse struct {
	StartedAt      *string          `json:"started_at,omitempty"`
	TotalRequests  *int64           `json:"total_requests,omitempty"`
	ActiveRequests *int64           `json:"active_requests,omitempty"`
	TotalErrors    *int64           `json:"total_errors,omitempty"`
	UptimeSeconds  *float64         `json:"uptime_seconds,omitempty"`
	RequestsByCode map[string]int64 `json:"requests_by_code,omitempty"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AuthResponse struct {
	TenantId  *string `json:"tenant_id,omitempty"`
	ApiKey    *string `json:"api_key,omitempty"`
	Name      *string `json:"name,omitempty"`
	Email     *string `json:"email,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type CreateKeyRequest struct {
	Label  *string  `json:"label,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
}

type APIKeyCreated struct {
	Id        *string  `json:"id,omitempty"`
	Key       *string  `json:"key,omitempty"`
	Prefix    *string  `json:"prefix,omitempty"`
	Label     *string  `json:"label,omitempty"`
	Scopes    []string `json:"scopes,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
}

type APIKeySummary struct {
	Id         *string  `json:"id,omitempty"`
	Prefix     *string  `json:"prefix,omitempty"`
	Label      *string  `json:"label,omitempty"`
	Scopes     []string `json:"scopes,omitempty"`
	LastUsedAt *string  `json:"last_used_at,omitempty"`
	RevokedAt  *string  `json:"revoked_at,omitempty"`
	CreatedAt  *string  `json:"created_at,omitempty"`
}

type Wallet struct {
	Id        *string `json:"id,omitempty"`
	PublicKey *string `json:"public_key,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type WalletCreated struct {
	Id        *string `json:"id,omitempty"`
	PublicKey *string `json:"public_key,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type WalletBalances struct {
	WalletId *string   `json:"wallet_id,omitempty"`
	Balances []Balance `json:"balances,omitempty"`
}

type Balance struct {
	AssetCode *string `json:"asset_code,omitempty"`
	Issuer    *string `json:"issuer,omitempty"`
	Balance   *string `json:"balance,omitempty"`
}

type CreateTrustlineRequest struct {
	AssetCode   string  `json:"asset_code"`
	AssetIssuer string  `json:"asset_issuer"`
	Limit       *string `json:"limit,omitempty"`
}

type TrustlineResponse struct {
	WalletId    *string `json:"wallet_id,omitempty"`
	AssetCode   *string `json:"asset_code,omitempty"`
	AssetIssuer *string `json:"asset_issuer,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type FiatQuotePreviewResponse struct {
	Provider     *string `json:"provider,omitempty"`
	FiatAmount   *string `json:"fiat_amount,omitempty"`
	FiatCurrency *string `json:"fiat_currency,omitempty"`
	UsdcAmount   *string `json:"usdc_amount,omitempty"`
	Rate         *string `json:"rate,omitempty"`
	Fee          *string `json:"fee,omitempty"`
	MinLimit     *string `json:"min_limit,omitempty"`
	MaxLimit     *string `json:"max_limit,omitempty"`
	ExpiresAt    *string `json:"expires_at,omitempty"`
}

type FiatDepositRequest struct {
	Amount   string `json:"amount"`
	Currency string `json:"currency"`
	Email    string `json:"email"`
	Name     string `json:"name"`
}

type CreatePaymentLinkRequest struct {
	WalletId  string `json:"wallet_id"`
	Amount    string `json:"amount"`
	Currency  string `json:"currency"`
	ExpiresAt string `json:"expires_at"`
}

type PaymentLinksResponse struct {
	PaymentLinks []PaymentLink `json:"payment_links"`
}

type PaymentLink struct {
	Id          string  `json:"id"`
	Token       string  `json:"token"`
	WalletId    string  `json:"wallet_id"`
	Amount      string  `json:"amount"`
	Currency    string  `json:"currency"`
	Status      string  `json:"status"`
	CheckoutUrl string  `json:"checkout_url"`
	ExpiresAt   string  `json:"expires_at"`
	CreatedAt   *string `json:"created_at,omitempty"`
}

type PublicPaymentLink struct {
	Amount    string `json:"amount"`
	Currency  string `json:"currency"`
	Status    string `json:"status"`
	ExpiresAt string `json:"expires_at"`
}

type Refund struct {
	Id                    string  `json:"id"`
	OriginalTransactionId string  `json:"original_transaction_id"`
	TransactionId         *string `json:"transaction_id,omitempty"`
	Amount                string  `json:"amount"`
	Reason                *string `json:"reason,omitempty"`
	Status                string  `json:"status"`
}

type CreateRefundRequest struct {
	OriginalTransactionId string  `json:"original_transaction_id"`
	Amount                string  `json:"amount"`
	Reason                *string `json:"reason,omitempty"`
}

type RefundsResponse struct {
	Refunds []Refund `json:"refunds"`
}

type DepositResponse struct {
	PaymentLink *string `json:"payment_link,omitempty"`
	Reference   *string `json:"reference,omitempty"`
}

type FiatWithdrawalRequest struct {
	Amount        string `json:"amount"`
	Currency      string `json:"currency"`
	AccountBank   string `json:"account_bank"`
	AccountNumber string `json:"account_number"`
}

type WithdrawalResponse struct {
	Reference *string `json:"reference,omitempty"`
	Status    *string `json:"status,omitempty"`
}

type FiatDeposit struct {
	Id                *string `json:"id,omitempty"`
	WalletId          *string `json:"wallet_id,omitempty"`
	Provider          *string `json:"provider,omitempty"`
	ProviderReference *string `json:"provider_reference,omitempty"`
	FiatAmount        *string `json:"fiat_amount,omitempty"`
	FiatCurrency      *string `json:"fiat_currency,omitempty"`
	UsdcAmount        *string `json:"usdc_amount,omitempty"`
	Status            *string `json:"status,omitempty"`
	CreatedAt         *string `json:"created_at,omitempty"`
}

type FiatWithdrawal struct {
	Id                *string `json:"id,omitempty"`
	WalletId          *string `json:"wallet_id,omitempty"`
	Provider          *string `json:"provider,omitempty"`
	ProviderReference *string `json:"provider_reference,omitempty"`
	FiatAmount        *string `json:"fiat_amount,omitempty"`
	FiatCurrency      *string `json:"fiat_currency,omitempty"`
	UsdcAmount        *string `json:"usdc_amount,omitempty"`
	Status            *string `json:"status,omitempty"`
	CreatedAt         *string `json:"created_at,omitempty"`
}

type CreateTransferRequest struct {
	FromWalletId      string   `json:"from_wallet_id"`
	ToWalletId        string   `json:"to_wallet_id"`
	Asset             string   `json:"asset"`
	Amount            string   `json:"amount"`
	ExternalReference *string  `json:"external_reference,omitempty"`
	Tags              []string `json:"tags,omitempty"`
}

type TransferResponse struct {
	Id                *string  `json:"id,omitempty"`
	TxHash            *string  `json:"tx_hash,omitempty"`
	Type              *string  `json:"type,omitempty"`
	Status            *string  `json:"status,omitempty"`
	FromWalletId      *string  `json:"from_wallet_id,omitempty"`
	ToWalletId        *string  `json:"to_wallet_id,omitempty"`
	Asset             *string  `json:"asset,omitempty"`
	Amount            *string  `json:"amount,omitempty"`
	FeeAmount         *string  `json:"fee_amount,omitempty"`
	NetAmount         *string  `json:"net_amount,omitempty"`
	FeeBps            *int64   `json:"fee_bps,omitempty"`
	ExternalReference *string  `json:"external_reference,omitempty"`
	Tags              []string `json:"tags,omitempty"`
	FailureReason     *string  `json:"failure_reason,omitempty"`
	FailureMessage    *string  `json:"failure_message,omitempty"`
	CreatedAt         *string  `json:"created_at,omitempty"`
}

type AuditEvent struct {
	Id           *string        `json:"id,omitempty"`
	TenantId     *string        `json:"tenant_id,omitempty"`
	Mode         *string        `json:"mode,omitempty"`
	ActorType    *string        `json:"actor_type,omitempty"`
	ActorId      *string        `json:"actor_id,omitempty"`
	Action       *string        `json:"action,omitempty"`
	ResourceType *string        `json:"resource_type,omitempty"`
	ResourceId   *string        `json:"resource_id,omitempty"`
	Metadata     map[string]any `json:"metadata,omitempty"`
	IpAddress    *string        `json:"ip_address,omitempty"`
	UserAgent    *string        `json:"user_agent,omitempty"`
	CreatedAt    *string        `json:"created_at,omitempty"`
}

type AuditListResponse struct {
	Events []AuditEvent `json:"events,omitempty"`
	Total  *int64       `json:"total,omitempty"`
	Limit  *int64       `json:"limit,omitempty"`
	Offset *int64       `json:"offset,omitempty"`
}

type CreateBatchRequest struct {
	FromWalletId string             `json:"from_wallet_id"`
	Transfers    []BatchItemRequest `json:"transfers"`
}

type BatchItemRequest struct {
	ToWalletId string  `json:"to_wallet_id"`
	Asset      string  `json:"asset"`
	Amount     string  `json:"amount"`
	Reference  *string `json:"reference,omitempty"`
}

type BatchResponse struct {
	Id           *string             `json:"id,omitempty"`
	Status       *string             `json:"status,omitempty"`
	TotalCount   *int64              `json:"total_count,omitempty"`
	SuccessCount *int64              `json:"success_count,omitempty"`
	FailedCount  *int64              `json:"failed_count,omitempty"`
	HeldCount    *int64              `json:"held_count,omitempty"`
	CreatedAt    *string             `json:"created_at,omitempty"`
	Transfers    []BatchTransferItem `json:"transfers,omitempty"`
}

type BatchTransferItem struct {
	Id             *string `json:"id,omitempty"`
	ToWalletId     *string `json:"to_wallet_id,omitempty"`
	Asset          *string `json:"asset,omitempty"`
	Amount         *string `json:"amount,omitempty"`
	Reference      *string `json:"reference,omitempty"`
	Status         *string `json:"status,omitempty"`
	TxHash         *string `json:"tx_hash,omitempty"`
	FailureReason  *string `json:"failure_reason,omitempty"`
	FailureMessage *string `json:"failure_message,omitempty"`
}

type QuoteRequest struct {
	FromAsset string `json:"from_asset"`
	ToAsset   string `json:"to_asset"`
	Amount    string `json:"amount"`
}

type Quote struct {
	Id         *string `json:"id,omitempty"`
	OrgId      *string `json:"org_id,omitempty"`
	FromAsset  *string `json:"from_asset,omitempty"`
	ToAsset    *string `json:"to_asset,omitempty"`
	FromAmount *string `json:"from_amount,omitempty"`
	ToAmount   *string `json:"to_amount,omitempty"`
	Rate       *string `json:"rate,omitempty"`
	Fee        *string `json:"fee,omitempty"`
	ExpiresAt  *string `json:"expires_at,omitempty"`
	Used       *bool   `json:"used,omitempty"`
}

type ConvertRequest struct {
	WalletId       string  `json:"wallet_id"`
	QuoteId        string  `json:"quote_id"`
	MinAmountOut   *string `json:"min_amount_out,omitempty"`
	MaxSlippageBps *int64  `json:"max_slippage_bps,omitempty"`
}

type ConversionResponse struct {
	Id           *string `json:"id,omitempty"`
	WalletId     *string `json:"wallet_id,omitempty"`
	SourceAsset  *string `json:"source_asset,omitempty"`
	DestAsset    *string `json:"dest_asset,omitempty"`
	SourceAmount *string `json:"source_amount,omitempty"`
	DestAmount   *string `json:"dest_amount,omitempty"`
	FeeAmount    *string `json:"fee_amount,omitempty"`
	FeeBps       *int64  `json:"fee_bps,omitempty"`
	Rate         *string `json:"rate,omitempty"`
	TxHash       *string `json:"tx_hash,omitempty"`
	CreatedAt    *string `json:"created_at,omitempty"`
}

type RateResponse struct {
	Rate          *string `json:"rate,omitempty"`
	MidMarketRate *string `json:"mid_market_rate,omitempty"`
	SpreadBps     *int64  `json:"spread_bps,omitempty"`
	Provider      *string `json:"provider,omitempty"`
	CachedAt      *string `json:"cached_at,omitempty"`
	Stale         *bool   `json:"stale,omitempty"`
	SourceAmount  *string `json:"source_amount,omitempty"`
	DestAmount    *string `json:"dest_amount,omitempty"`
	FeeAmount     *string `json:"fee_amount,omitempty"`
	NetAmount     *string `json:"net_amount,omitempty"`
	FeeBps        *int64  `json:"fee_bps,omitempty"`
}

type CreateScheduleRequest struct {
	FromWalletId    string  `json:"from_wallet_id"`
	ToWalletId      string  `json:"to_wallet_id"`
	Asset           string  `json:"asset"`
	Amount          string  `json:"amount"`
	Frequency       string  `json:"frequency"`
	Timezone        *string `json:"timezone,omitempty"`
	MissedRunPolicy *string `json:"missed_run_policy,omitempty"`
	StartDate       string  `json:"start_date"`
	EndDate         *string `json:"end_date,omitempty"`
}

type ScheduleRunResponse struct {
	Id            *string `json:"id,omitempty"`
	ScheduleId    *string `json:"schedule_id,omitempty"`
	ExpectedRunAt *string `json:"expected_run_at,omitempty"`
	Status        *string `json:"status,omitempty"`
	TransactionId *string `json:"transaction_id,omitempty"`
	Error         *string `json:"error,omitempty"`
	StartedAt     *string `json:"started_at,omitempty"`
	CompletedAt   *string `json:"completed_at,omitempty"`
	CreatedAt     *string `json:"created_at,omitempty"`
}

type UpdateScheduleRequest struct {
	Status          *string `json:"status,omitempty"`
	Amount          *string `json:"amount,omitempty"`
	Frequency       *string `json:"frequency,omitempty"`
	EndDate         *string `json:"end_date,omitempty"`
	Timezone        *string `json:"timezone,omitempty"`
	MissedRunPolicy *string `json:"missed_run_policy,omitempty"`
}

type ScheduleResponse struct {
	Id              *string `json:"id,omitempty"`
	FromWalletId    *string `json:"from_wallet_id,omitempty"`
	ToWalletId      *string `json:"to_wallet_id,omitempty"`
	Asset           *string `json:"asset,omitempty"`
	Amount          *string `json:"amount,omitempty"`
	Frequency       *string `json:"frequency,omitempty"`
	Timezone        *string `json:"timezone,omitempty"`
	MissedRunPolicy *string `json:"missed_run_policy,omitempty"`
	NextRunAt       *string `json:"next_run_at,omitempty"`
	EndAt           *string `json:"end_at,omitempty"`
	Status          *string `json:"status,omitempty"`
	CreatedAt       *string `json:"created_at,omitempty"`
}

type RegisterWebhookRequest struct {
	Url    string   `json:"url"`
	Events []string `json:"events,omitempty"`
}

type WebhookEndpointResponse struct {
	Id        *string  `json:"id,omitempty"`
	Url       *string  `json:"url,omitempty"`
	Secret    *string  `json:"secret,omitempty"`
	Events    []string `json:"events,omitempty"`
	Active    *bool    `json:"active,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
}

type WebhookEndpointSummary struct {
	Id        *string  `json:"id,omitempty"`
	Url       *string  `json:"url,omitempty"`
	Events    []string `json:"events,omitempty"`
	Active    *bool    `json:"active,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
}

type WebhookDelivery struct {
	Id           *string `json:"id,omitempty"`
	EndpointId   *string `json:"endpoint_id,omitempty"`
	EventType    *string `json:"event_type,omitempty"`
	Status       *string `json:"status,omitempty"`
	ResponseCode *int64  `json:"response_code,omitempty"`
	AttemptCount *int64  `json:"attempt_count,omitempty"`
	LastAttempt  *string `json:"last_attempt,omitempty"`
	CreatedAt    *string `json:"created_at,omitempty"`
}

type FeeScheduleResponse struct {
	TransferFeeBps   *int64  `json:"transfer_fee_bps,omitempty"`
	ConversionFeeBps *int64  `json:"conversion_fee_bps,omitempty"`
	MinFeeAmount     *string `json:"min_fee_amount,omitempty"`
	MaxFeeAmount     *string `json:"max_fee_amount,omitempty"`
	Asset            *string `json:"asset,omitempty"`
}

type FeeCollectionSummary struct {
	Asset      *string          `json:"asset,omitempty"`
	TotalFees  *string          `json:"total_fees,omitempty"`
	TenantFees []TenantFeeTotal `json:"tenant_fees,omitempty"`
}

type TenantFeeTotal struct {
	TenantId  *string `json:"tenant_id,omitempty"`
	TotalFees *string `json:"total_fees,omitempty"`
}

type ClaimPredicate struct {
	Type       string           `json:"type"`
	Timestamp  *int64           `json:"timestamp,omitempty"`
	Seconds    *int64           `json:"seconds,omitempty"`
	Predicates []ClaimPredicate `json:"predicates,omitempty"`
}

type Claimant struct {
	Account   string          `json:"account"`
	Predicate *ClaimPredicate `json:"predicate,omitempty"`
}

type CreateClaimableBalanceRequest struct {
	Asset          string     `json:"asset"`
	Amount         string     `json:"amount"`
	Claimants      []Claimant `json:"claimants"`
	SourceWalletId *string    `json:"source_wallet_id,omitempty"`
	SponsorAccount *string    `json:"sponsor_account,omitempty"`
	RevokeOnExpiry *bool      `json:"revoke_on_expiry,omitempty"`
	ExpiresAt      *string    `json:"expires_at,omitempty"`
}

type CreateClaimableBalanceResponse struct {
	BalanceId       *string `json:"balance_id,omitempty"`
	ReserveRequired *string `json:"reserve_required,omitempty"`
	Sponsored       *bool   `json:"sponsored,omitempty"`
	TxHash          *string `json:"tx_hash,omitempty"`
	ExpiresAt       *string `json:"expires_at,omitempty"`
}

type ClaimableBalanceResponse struct {
	Id             *string    `json:"id,omitempty"`
	Asset          *string    `json:"asset,omitempty"`
	Amount         *string    `json:"amount,omitempty"`
	Claimants      []Claimant `json:"claimants,omitempty"`
	Sponsor        *string    `json:"sponsor,omitempty"`
	Status         *string    `json:"status,omitempty"`
	RevokeOnExpiry *bool      `json:"revoke_on_expiry,omitempty"`
	CreatedAt      *string    `json:"created_at,omitempty"`
	ExpiresAt      *string    `json:"expires_at,omitempty"`
	ClaimedAt      *string    `json:"claimed_at,omitempty"`
	ClaimedBy      *string    `json:"claimed_by,omitempty"`
}

type LiveClaimableBalanceResponse struct {
	ClaimableBalanceResponse
	Claimable *bool          `json:"claimable,omitempty"`
	OnChain   map[string]any `json:"on_chain,omitempty"`
}

type ClaimClaimableBalanceRequest struct {
	ClaimantAccount *string `json:"claimant_account,omitempty"`
}

type ClaimClaimableBalanceResponse struct {
	BalanceId *string `json:"balance_id,omitempty"`
	ClaimedBy *string `json:"claimed_by,omitempty"`
	Amount    *string `json:"amount,omitempty"`
	TxHash    *string `json:"tx_hash,omitempty"`
	Status    *string `json:"status,omitempty"`
}

type UsageResponse struct {
	TotalRequests    *int64 `json:"total_requests,omitempty"`
	RequestsToday    *int64 `json:"requests_today,omitempty"`
	TransfersCount   *int64 `json:"transfers_count,omitempty"`
	ConversionsCount *int64 `json:"conversions_count,omitempty"`
	BatchesCount     *int64 `json:"batches_count,omitempty"`
}

type ReconciliationSummary struct {
	Days          []DailySummaryRow `json:"days,omitempty"`
	TotalOk       *int64            `json:"total_ok,omitempty"`
	TotalMismatch *int64            `json:"total_mismatch,omitempty"`
	TotalNotFound *int64            `json:"total_not_found,omitempty"`
	PendingStuck  *int64            `json:"pending_stuck,omitempty"`
}

type DailySummaryRow struct {
	Date     *string `json:"date,omitempty"`
	Ok       *int64  `json:"ok,omitempty"`
	Mismatch *int64  `json:"mismatch,omitempty"`
	NotFound *int64  `json:"not_found,omitempty"`
}

type IdempotencyInspectionResponse struct {
	Key               string                     `json:"key"`
	Status            string                     `json:"status"`
	CreatedAt         *string                    `json:"created_at,omitempty"`
	ExpiresAt         *string                    `json:"expires_at,omitempty"`
	RequestHash       *string                    `json:"request_hash,omitempty"`
	RetryAfterSeconds *int64                     `json:"retry_after_seconds,omitempty"`
	RetryHint         *string                    `json:"retry_hint,omitempty"`
	Response          *IdempotencyStoredResponse `json:"response,omitempty"`
}

type IdempotencyStoredResponse struct {
	Status        int64               `json:"status"`
	Headers       map[string][]string `json:"headers,omitempty"`
	Body          any                 `json:"body,omitempty"`
	BodyText      *string             `json:"body_text,omitempty"`
	BodyTruncated bool                `json:"body_truncated"`
	BodySizeBytes int64               `json:"body_size_bytes"`
}
